apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pvu4rekkb-dotnet-basic
  janus-idp.io/tekton: pvu4rekkb-dotnet-basic
  backstage.io/kubernetes-id: pvu4rekkb-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pvu4rekkb-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
